<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.2" tiledversion="1.3.2" name="TestTile" tilewidth="64" tileheight="64" tilecount="136" columns="8">
 <image source="tiles.png" width="512" height="1088"/>
 <tile id="4" type="floor"/>
 <tile id="5" type="hole"/>
 <tile id="7" type="wall_r_s"/>
 <tile id="12" type="up_b"/>
 <tile id="13" type="right_b"/>
 <tile id="15" type="wall_r_u"/>
 <tile id="16" type="down_b"/>
 <tile id="17" type="left_b"/>
 <tile id="18" type="right_b"/>
 <tile id="19" type="down_b"/>
 <tile id="20" type="down_b"/>
 <tile id="21" type="left_b"/>
 <tile id="22" type="wall_r"/>
 <tile id="23" type="wall_u_l"/>
 <tile id="24" type="right_b"/>
 <tile id="25" type="up_b"/>
 <tile id="26" type="up_b"/>
 <tile id="27" type="left_b"/>
 <tile id="28" type="wall_d"/>
 <tile id="29" type="wall_l"/>
 <tile id="30" type="wall_u"/>
 <tile id="31" type="wall_l_d"/>
 <tile id="32" type="down_y"/>
 <tile id="33" type="left_y"/>
 <tile id="34" type="rigth_y"/>
 <tile id="35" type="down_y"/>
 <tile id="36" type="wall_d"/>
 <tile id="37" type="wall_l"/>
 <tile id="38" type="laser_single"/>
 <tile id="39" type="laser_double"/>
 <tile id="40" type="rigth_y"/>
 <tile id="41" type="up_y"/>
 <tile id="42" type="up_y"/>
 <tile id="43" type="left_y"/>
 <tile id="44" type="wall_u"/>
 <tile id="45" type="wall_l"/>
 <tile id="46" type="laser_single"/>
 <tile id="48" type="up_y"/>
 <tile id="49" type="down_y"/>
 <tile id="50" type="left_y"/>
 <tile id="51" type="rigth_y"/>
 <tile id="54" type="flag1"/>
 <tile id="56" type="up_y"/>
 <tile id="57" type="rigth_y"/>
 <tile id="58" type="down_y"/>
 <tile id="59" type="left_y"/>
 <tile id="60" type="rigth_y"/>
 <tile id="61" type="down_y"/>
 <tile id="62" type="flag2"/>
 <tile id="64" type="up_y"/>
 <tile id="65" type="rigth_y"/>
 <tile id="66" type="down_y"/>
 <tile id="67" type="left_y"/>
 <tile id="68" type="up_y"/>
 <tile id="69" type="left_y"/>
 <tile id="70" type="flag3"/>
 <tile id="72" type="up_b"/>
 <tile id="73" type="right_b"/>
 <tile id="74" type="down_b"/>
 <tile id="75" type="left_b"/>
 <tile id="76" type="up_b"/>
 <tile id="77" type="right_b"/>
 <tile id="78" type="flag4"/>
 <tile id="80" type="right_b"/>
 <tile id="81" type="down_b"/>
 <tile id="82" type="left_b"/>
 <tile id="83" type="up_b"/>
 <tile id="84" type="left_b"/>
 <tile id="85" type="down_b"/>
 <tile id="100" type="laser_quad"/>
 <tile id="101" type="laser_double"/>
 <tile id="102" type="laser_double"/>
 <tile id="120" type="player_start_1"/>
 <tile id="121" type="player_start_2"/>
 <tile id="122" type="player_start_3"/>
 <tile id="123" type="player_start_4"/>
 <tile id="128" type="player_start_5"/>
</tileset>
